# theme: jekyll-theme-cayman
# title: My Data Science Portfolio
# description: Here are some of my key data science projects and notable accomplishments

# Theme configuration
theme: beautiful-jekyll

# Basic settings
title: My Data Science Portfolio
description: Here are some of my key data science projects and notable accomplishments


# Kramdown settings
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'

# Logo & Favicon (Assuming you have them in the assets folder)
logo: "/assets/logo.png"
favicon: "/assets/favicon.ico"

# Navigation links
nav:
  - name: "About"
    link: "/about/"
  - name: "Projects"
    link: "/projects/"
  - name: "Blog"
    link: "/blog/"

# Social media and other links
# Replace '#username' with your usernames or links
social:
  - name: "github"
    link: "https://github.com/#username"
  - name: "linkedin"
    link: "https://www.linkedin.com/in/#username"
  - name: "twitter"
    link: "https://twitter.com/#username"

# Google Analytics (optional - remove or replace with your tracking ID if you want to use it)
# google_analytics: "UA-XXXXXXXXX-X"

# Disqus commenting (optional - replace with your Disqus shortname if you want to use it)
# disqus:
#   shortname: your_disqus_shortname
