theme: jekyll-theme-cayman
title: My Data Science Portfolio
description: Here are some of my key data science projects and notable accomplishments

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

footer:
  links:
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/michaeldiamond2/"
    - title: "GitHub"
      url: "https://github.com/micdiamond/"

